### ISSUE TITLE
Absence of quality flags

### ISSUE THREAD

**Issue by BaptisteVandecrux** [EnviDat/monitoring-backend#3]
Currently no data quality flags are provided, not even the native ones distributed by Koni.
The Envidat processing seem to run some tests that could also be used for flagging.

Derek:
> The old matlab processing routine used a gradient filter (preventing single point jumps over a certain threshold). See attached filter description, it is not fully complete but shows the hard-coded thresholds input to "GradientCleaning" function used in the matlab software. These filters have not been applied to the satellite transmitted data.
The transmitted data has only been calibrated and max/min limited in the python processor.
I still need to find a more intelligent way to filter the snow height data. This was what was mostly manually filtered in the past as these tend to be the noisiest measurements. I am looking into a median absolute deviation filter and other statistical filtering methods.

**Comment by BaptisteVandecrux** [comment]
[GC-Net Matlab filtering protocol](https://github.com/GEUS-PROMICE/PROMICE-AWS-toolbox/blob/master/doc/GC-NET_MATLAB_filter_description.docx)

**Comment by iosifescu** [comment]
@houtzd @BaptisteVandecrux : 
FYI, quality flags (if provided by Derek) can be implemented in our EnviDat database and NEAD export, and exported in NEAD format with field_Q (as suggested by @mankoff), with the following restrictions:
- _Q will only contain codes/numbers
- the human descriptions for the codes are included only once in the header
- the number of different quality flags possible (in one NEAD file) should be limited to a maximum of 64 different flags
