### ISSUE TITLE
Crawford point request failed

### ISSUE THREAD

**Issue by BaptisteVandecrux** [EnviDat/monitoring-backend#5]
Hi,

I tried the following request:
https://www.envidat.ch/data-api/gcnet/nead/crawfordpoint/end/-999/2019-05-11/2022-04-25/

it gave me:
Page not found
Non-valid 'model' (station) entered in URL: crawfordpoint
Valid models are listed at: https://www.envidat.ch/data-api/gcnet/models/

I can see that the station is not listed in  https://www.envidat.ch/data-api/gcnet/models/
but it still appears on: https://www.envidat.ch/data-api/gcnet/

**Comment by BaptisteVandecrux** [comment]
Same thing for GITS, Tunu-N and JAR1

**Comment by rebeccabuchholz** [comment]
Tunu-N and JAR1 were reactivated and the data for these stations are now accessible.

It will take some time to make the GITS data accessible again because the GITS satellite station ID was used for another station in Antarctica.

**Comment by rebeccabuchholz** [comment]
GITS data is now accessible.

For GC-Net API documentation please see https://www.envidat.ch/data-api/gcnet/

**Comment by BaptisteVandecrux** [comment]
Thanks!
